"""
File name:      ErrorWarningConsts.py
Author:         Sebastian Seidel
Date:           2023-12-**
Description:
"""
ERROR_FILE_NOT_EXIST = "e10"
ERROR_PATH_NOT_EXIST = "e11"
ERROR_NO_FILES_FOUND = "e12"
ERROR_NO_DWD_STATIONDATA_FOUND = "e13"
ERROR_INIT_FILE_NOT_EXIST = "e14"
ERROR_CORRUPT_INIT_FILES = "e15"

ERROR_PARAM_NOT_EXIST = "e20"
ERROR_WRONG_MODEL = "e21"

ERROR_UNSTRUCTURED_GRID = "e30"
ERROR_GRIB2_FILES_INCOMPLETE = "e31"
ERROR_DATETIME_NOT_IN_RANGE = "e32"
ERROR_LAT_OUT_OF_RANGE = "e33"
ERROR_LON_OUT_OF_RANGE = "e34"

WARNING_SOME_FILES_ARE_INVALID = "w10"
WARNING_SOME_STATIONS_UNLOADED = "w11"




