"""
File name:      ErrorWarningConsts.py
Author:         Sebastian Seidel
Date:           2023-12-**
Description:
"""
ERROR_FILE_NOT_EXIST: str = "e10"
ERROR_PATH_NOT_EXIST: str = "e11"
ERROR_NO_FILES_FOUND: str = "e12"
ERROR_NO_DWD_STATIONDATA_FOUND: str = "e13"
ERROR_INIT_FILE_NOT_EXIST: str = "e14"
ERROR_CORRUPT_INIT_FILES: str = "e15"

ERROR_PARAM_NOT_EXIST: str = "e20"
ERROR_WRONG_MODEL: str = "e21"

ERROR_UNSTRUCTURED_GRID: str = "e30"
ERROR_GRIB2_FILES_INCOMPLETE: str = "e31"
ERROR_DATETIME_NOT_IN_RANGE = "e32"
ERROR_LAT_OUT_OF_RANGE: str = "e33"
ERROR_LON_OUT_OF_RANGE: str = "e34"

WARNING_SOME_FILES_ARE_INVALID: str = "w10"
WARNING_SOME_STATIONS_UNLOADED: str = "w11"




